[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
anyhow = "1.0"
zip = "5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
